= System Control/Symbology

Successful operating missions require operators to have a solid understanding of the system
operating modes; how to select and control these operating modes; and how to select and
interpret the display screen symbology.
This chapter provides System Control Unit (SCU) and display screen symbology for the Star
SAFIRE(C) 380-HD system.

== Operational Limitations

This section provides operation recommendations including airspeed, if applicable, and crash
damage.

=== Airspeed

Teledyne FLIR recommends a maximum airspeed for system operations.

CAUTION: Flights exceeding a maximum airspeed of 415 Knots could damage the TFU.

=== Crash Damage

In the event of a crash, systems are known to exhibit broken windows with cracked or large
shards of glass fragments inside the TFU and on the ground at the crash site. Proper handling
of Teledyne FLIR equipment (LRUs) are covered in this section.

==== First Responders
First Responders include Rescue Crew, Aircrew, and Aircraft Maintenance Crew. This section
provides hazards and equipment requirements.

WARNING: While there are no specialized identified Personal Protective Equipment
(PPE), Teledyne FLIR strongly recommends use of thick or heavy leather
gloves while handling of TFUs with broken windows or fractured housing
material.

WARNING: Use extreme care when handling shards of broken or cracked glass
fragments.

Requirements are as follows:

* Environmental Hazards: None
* Chemical Hazards: None
* Ozone Depleting Chemicals: None
* Personal Protective Equipment (PPE): Protective gloves (for broken glass)

== Operational Techniques
Understanding the concepts of infrared (IR) imaging, good crew coordination, learning and
practicing the various system modes of operation, and sharing information and techniques with
other operators and departments will ensure successful missions.

=== Crew Operation
Good communication between the aircraft pilot, ground personnel, or another ground station
results in safer, more successful missions.
One operating challenge is to correctly determine the direction and tracking of a moving target
and then follow it. The system needs to be constantly adjusted for platform movement, target
movement, and Line-of-Sight (LOS). Crew coordination is key to success.

=== Successful Operating Ideas
In order to maximize successful mission completion, operators should become familiar with the
system. Here are some tips and suggestions to increase mission success.
The following operating suggestions are provided to aid operators:

CAUTION: For non-maritime model TFUs, do not install, operate, or store the TFU in the
ball up configuration when exposed to the elements. Water intrusion may
occur in the skillet during heavy inclement weather.

CAUTION: Do not store the TFU for long periods with the lenses facing the sun. Long
term exposure to the sun will damage the system optics.

[NOTE]
====
The following target approaches can cause erratic gimbal behavior and should be
avoided during operation:

. ball-down systems, –90° elevation (nadir)
. ball-
up systems ,+90° elevation (zenith).
====

NOTE: If
the
IR
sensor
approaches
over-heating
(in
extreme
high
temperature
environments such as in the desert), the system will shut the IR sensor down. This
is similar to the hibernate mode. If this occurs, all other sensors will be available.
Once the system cools down, the IR sensor will again be available for use.

* Develop a solid understanding of thermal imaging as opposed to visible light, and the impact
of environmental factors on the images.
* Build video libraries for review, instruction, and reference. Share tactics, techniques, and
procedures with other operators and departments.
* Learn to adjust the system according to the existing or changing environmental conditions.
Proper Grayscale, Scene Temperature, and Gain / Level adjustment enhances the display
for even minor target temperature variations.
* Practice finding and tracking various thermal cues, which can be ’hot,’ ‘cold,’ or somewhere
in between, depending on the situation. When using an Infrared (IR) sensor, the operator
must keep in mind the visual cues he/she is used to seeing with his/her eyes will be
presented differently. The operator needs to understand how to interpret the scene in order
to provide useful narration or direction to others during a mission.
* Search in wider fields of view and identify in narrower fields of view.

== Modes of Operation
Various turret control modes and image optimization settings are available to help operators
successfully complete mission objectives.
The most commonly used functions are shown in the table below.

.Modes of Operation
[options="header"]
|===
|Turret Control Mode|Image Optimization
|Cage (CAGE) & Stow (STOW)|Polarity (POL)
|Inertial Point (IP)|Focus - Auto & Manual
|Heading Hold (HH)|Gain and Level /Exposure (Auto, Manual, Histogram)
|Rate Aid (RA)|Non-Uniformity Correction (NUC)
|Geopoint (GEOPOINT); Image Aid Geopoint(GEOPOINT–IA)|Field-of-View Change
|Tracking|Scene Temperature
|===